name: apt

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  apt:
    runs-on: ubuntu-latest
    steps:
      - name: look at sources
        run: |
          (
            for a in /etc/apt/sources.list.d/* /etc/apt/sources.list /etc/apt/apt-mirrors.txt; do
              echo '# '$(basename $a)
              echo
              echo '```'
              cat $a
              echo '```'
              echo
            done
          ) >> "$GITHUB_STEP_SUMMARY"
      - name: update
        run: |
          sudo apt-get update

      - name: rewrite sources
        run: |
          (
            printf "http://azure.archive.ubuntu.com/ubuntu/\tpriority:4\n"
            printf "https://archive.ubuntu.com/ubuntu/\tpriority:2\n"
            printf "https://security.ubuntu.com/ubuntu/\tpriority:3\n"
          ) | sudo tee /etc/apt/apt-mirrors.txt

      - name: update
        run: |
          sudo apt-get update

      - name: rewrite sources
        run: |
          (
            printf "http://azure.archive.ubuntu.com/not-ubuntu/\tpriority:1\n"
            printf "https://archive.ubuntu.com/ubuntu/\tpriority:2\n"
            printf "https://security.ubuntu.com/ubuntu/\tpriority:3\n"
          ) | sudo tee /etc/apt/apt-mirrors.txt

      - name: update
        run: |
          sudo apt-get update

