name: apt

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  apt:
    runs-on: ubuntu-latest
    permissions: ''
    steps:
      - uses: step-security/harden-runner@c6295a65d1254861815972266d5933fd6e532bdf # v2.11.1
        name: Harden Runner
        with:
          egress-policy: block
          allowed-endpoints: >
            archive.ubuntu.com:443
            esm.ubuntu.com:443
            packages.microsoft.com:443
      - name: look at sources
        run: |
          (
            for a in /etc/apt/sources.list.d/* /etc/apt/sources.list /etc/apt/apt-mirrors.txt; do
              echo '# '$(basename $a)
              echo
              echo '```'
              cat $a
              echo '```'
              echo
            done
          ) >> "$GITHUB_STEP_SUMMARY"
      - name: update
        run: |
          sudo apt-get update

      - name: rewrite ubuntu.sources
        run: |
          is_ubuntu24() {
              lsb_release -rs | grep -q '24.04'
          }
          ubuntu_sources=$(
            if is_ubuntu24; then
                echo /etc/apt/sources.list.d/ubuntu.sources
            else
                echo /etc/apt/sources.list
            fi
          )
          sudo sed -i 's/http:\/\/azure.archive.ubuntu.com\/ubuntu\//mirror+file:\/etc\/apt\/apt-mirrors.txt/' "$ubuntu_sources"
          (
            for a in "$ubuntu_sources"; do
              echo '# '$(basename $a)
              echo
              echo '```'
              cat $a
              echo '```'
              echo
            done
          ) >> "$GITHUB_STEP_SUMMARY"

      - name: rewrite sources
        run: |
          (
            printf "http://azure.archive.ubuntu.com/ubuntu/\tpriority:4\n"
            printf "https://archive.ubuntu.com/ubuntu/\tpriority:2\n"
            printf "https://security.ubuntu.com/ubuntu/\tpriority:3\n"
          ) | sudo tee /etc/apt/apt-mirrors.txt

      - name: update
        run: |
          sudo apt-get update

      - name: rewrite sources
        run: |
          (
            printf "http://azure.archive.ubuntu.com/not-ubuntu/\tpriority:1\n"
            printf "https://archive.ubuntu.com/ubuntu/\tpriority:2\n"
            printf "https://security.ubuntu.com/ubuntu/\tpriority:3\n"
          ) | sudo tee /etc/apt/apt-mirrors.txt

      - name: update
        run: |
          sudo apt-get update

